version: '3.7'
services:
  symfony-php:
    build: './docker/php'
    container_name: symfony-php
    # ports: ['9000:9000']
    volumes: ['./app/:/var/www/app:cached']
    networks:
      - 1panel-network
  symfony-nginx:
    build: './docker/nginx'
    container_name: symfony-nginx
    ports: ['61061:80']
    volumes: ['./app/:/var/www/app:cached']
    networks:
      - 1panel-network
  symfony-mongo:
    image: mongo
    container_name: symfony-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true